#include "HBMappingAlgorithm.h"
#include "HEMappingAlgorithm.h"
#include "ngHBMappingAlgorithm.h"
#include "ngHEMappingAlgorithm.h"
#include "HFMappingAlgorithm.h"
#include "ngHFMappingAlgorithm.h"
#include "HOMappingAlgorithm.h"
#include "ngHOMappingAlgorithm.h"
